### ISSUE TITLE
Får ikke lagret uten å velge symptomer

### ISSUE THREAD

**Issue by maccyber** [BustByte/coronastatus.no#15]
Hvis man klikker på lagre uten å ha valgt symptomer, får man følgende melding:

```An invalid form control with name='symptom-start' is not focusable.```

![non-selected](https://user-images.githubusercontent.com/701351/76706404-86025600-66e7-11ea-9608-724800cac276.png)

Dette er fordi symptom-start input elementet har attributten `required` https://github.com/BustByte/coronastatus.no/blob/03e9117ee99ca3cc472bc4cab12855c5a4b36c26/app/views/pages/form.ejs#L131

> This issue occurs on Chrome if a form field fails validation, but due to the respective invalid control not being focusable the browser's attempt to display the message "Please fill out this field" next to it fails as well.

**Comment by fossecode** [comment]
Fikset i https://github.com/BustByte/coronastatus.no/commit/2f735ca3f32f1f2e2ecc4923dc96889bd6ba303c
