### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#166]

**Comment by adriaandotcom** [comment]
I think it's important that issue happens first, because it's likely to cause merge conflicts with other PRs. Maybe after we have a list of translations we do this directly?

**Comment by fossecode** [comment]
Currently working on it. We should probably at least support english as well.

**Comment by ian-starts** [comment]
@fossecode Need help implementing i18n?

**Comment by Kilian** [comment]
We can use the same proposed google sheet to translate to english and dutch, a column each. Then we can use that to expand to other languages too.

**Comment by fossecode** [comment]
@ian-starts Thanks for asking, I can set up the basic stuff first. It would be great if we could start translating in a google sheet. @michaelmcmillan could you look at translating Norwegian -> English?

**Comment by michaelmcmillan** [comment]
Yes, I can translate from Norwegian to English. How should I do it? Just branch out, or add i18n?

**Comment by fossecode** [comment]
Any comments on this approach? https://github.com/BustByte/coronastatus/pull/169

Yell out if you have any other thoughts

**Comment by fossecode** [comment]
@Kilian did you create a spreadsheet?

**Comment by Kilian** [comment]
Here's the plan:
* [Here is the google sheet](https://docs.google.com/spreadsheets/d/1rgtSlCiI7pfOA6G9WU56LWK9qHn2tHxFNxkJQDXLbyQ/edit?usp=sharing), I'll start copying strings over from the EJS files.
* There are four columns: KEY, Norwegian, which I'll copy over, and empty Dutch and English
* Filling in the Dutch and English translation is a free for all: 
1. empty space: click on it so it's locked, find the translation, fill it in, move to the next
2. filled translation: click on it so it's locked, check if you agree, then make the cell green. If you don't agree, update and someone else will check

This way, translations are seen by at least two people without it being a hassle or blocking.

* Green translations can be added to the repo. Not sure what the best course of action for that is (considering prevention of merge conflicts on the translation files) but maybe someone has an idea there (like, add the KEY to the sheet first? i dunno)
