### ISSUE TITLE
Get zip codes with coordinates for the Netherlands into the app

### ISSUE THREAD

**Issue by michaelmcmillan** [BustByte/coronastatus.no#167]
Here are the things we need to solve:
* Create a copy of [`municipalities.json`](https://github.com/BustByte/coronastatus/blob/master/municipalities.json) where the key is the municipality and the zip codes are the zip codes within that municipality.
*  Create a copy of [`postalCodeCoordinates.json`](https://github.com/BustByte/coronastatus/blob/master/postalCodeCoordinates.json) where the zip code is the key and the coordinates are where the latitude and longitude of that zip code (WGS 84 coordinate system). 

I found these two files, but I'm struggling a little bit with figuring out what a municipality in the Netherlands how a zip code relates to that. 
[NL.txt](https://github.com/BustByte/coronastatus/files/4365112/NL.txt)
[readme.txt](https://github.com/BustByte/coronastatus/files/4365113/readme.txt)

**Comment by gavinhewitt** [comment]
The fifth column is the municipality

**Comment by michaelmcmillan** [comment]
Thank you @gavinhewitt. I'll use that.

**Comment by sbocinec** [comment]
Adding location data for Slovakia (not creating another issue for this) : [location_data_SK.zip](https://github.com/BustByte/coronastatus/files/4365208/location_data_SK.zip)

**Comment by fossecode** [comment]
Can we close this issue?

**Comment by michaelmcmillan** [comment]
Yep
