### ISSUE TITLE
Translation efforts for Dutch and English

### ISSUE THREAD

**Issue by Kilian** [BustByte/coronastatus.no#171]
**Update** translations are ongoing, see [this comment](https://github.com/BustByte/coronastatus/issues/171#issuecomment-602098143) for the plan.

----
* [Here is the google sheet](https://docs.google.com/spreadsheets/d/1rgtSlCiI7pfOA6G9WU56LWK9qHn2tHxFNxkJQDXLbyQ/edit?usp=sharing), I'll start copying strings over from the EJS files.
* There are four columns: KEY, Norwegian, which I'll copy over, and empty Dutch and English
* Filling in the Dutch and English translation is a free for all: 
1. empty space: click on it so it's locked, find the translation, fill it in, move to the next
2. filled translation: click on it so it's locked, check if you agree, then make the cell green. If you don't agree, update and someone else will check

This way, translations are seen by at least two people without it being a hassle or blocking.

* Green translations can be added to the repo. Not sure what the best course of action for that is (considering prevention of merge conflicts on the translation files) but maybe someone has an idea there (like, add the KEY to the sheet first? i dunno)

**Comment by Kilian** [comment]
**Update**: Dutch is fully translated, please review lines and fill them with green if you agree with them, or rephrase them and leave them white.

**Comment by Kilian** [comment]
**Update**: English is fully translated, please review lines and fill them with green if you agree with them, or rephrase them and leave them white. Same for the remaining white Dutch lines!

**Comment by Kilian** [comment]
**Update**: English is green and ready to be implemented! :tada:

**Comment by Kilian** [comment]
Claim your view here, then add translations from the translations sheet (some translations are used on multiple pages, so be sure to check you're not adding doubles)

* ~app/views/pages/404.ejs @Kilian~
* ~app/views/pages/500.ejs @Kilian~
* ~app/views/pages/confirm-profile.ejs @Kilian~
* ~app/views/pages/frivillige.ejs @Kilian~
* ~app/views/pages/helsenorge.ejs~
* ~app/views/pages/map.ejs~
* ~app/views/pages/privacy-policy.ejs~
* ~app/views/pages/report.ejs~
* ~app/views/pages/statistics.ejs~
* ~app/views/partials/disclaimer.ejs~
* ~app/views/partials/footer.ejs @zacel~
* ~app/views/partials/hamburger-menu.ejs @kilian~
* ~app/views/partials/head.ejs~
* ~app/views/partials/menu.ejs @Kilian~

If you claim one, let me know in a comment down below and I'll put your name in the list here, then after a PR it can be struck from the list.

Please make a PR against the `translations` branch, and commit the locale json files **with** trialing comma. That's invalid json, but it'll make diffs and merge conflicts easier to understand, and we'll fix it when we merge the translations branch back.

**Comment by jelbazi** [comment]
Did "app/views/pages/helsenorge.ejs". Some pc problems now. Will make PR in a bit. Then continue with others.
Also added to the locales too btw.

**Comment by ian-starts** [comment]
I'll claim "app/views/partials/head.ejs"

**Comment by Kilian** [comment]
PR in #205, closing this :tada:
