### ISSUE TITLE
Enhancement: easier data edit on repeat visit

### ISSUE THREAD

**Issue by kaared** [BustByte/coronastatus.no#172]
Currently a unique phrase is generated and displayed when the user submits the data form. The user is requested to make a note of the phrase so that he can revisit the site and update the submitted data later. This may create some friction or unnecessary work for the user which may cause them to not be able to update their entry or submit duplicate data.

Suggestion:

Consider creating and displaying the phrase as done already, but also include a link that the user can click and bookmark. The link contains the generated phrase. Clicking the link shows the form with the user's already submitted data (edit view). 

Also consider setting a cookie with the phrase and date of last update. The cookie is used to show edit view as above. This will also support a call to action when the user later visits the site. It also helps the user if they for some reason don't bookmark the previous link or make a note of the code. The CTA can then say something like: "It's been 3 days since you updated your situation. Has anything changed? Please update."

Summary: create parameterized link for bookmarking + set phrase in cookie and show edit view with CTA on repeat visit.

**Comment by fossecode** [comment]
👍 if we are going to use a cookie or saving data in local storage, the user needs to opt in to this (e.g checkbox or button). The users health information is practically stored in the browser.

**Comment by kaared** [comment]
Yes, completely agree. Using a cookie must be clearly communicated to and accepted by the user. My understanding is that since there's no PII (personally identifiable information) this is acceptable (at least to Norwegian authorities ref Slack discussions) or at least far less severe than if there was any PII. Forgot to mention that the cookie must be sticky, i.e survive window closures and browser restarts.

**Comment by arildwtv** [comment]
I see that @adriaanvanrossum implemented this - awesome! Should we close this?

I also think we should implement the "call-to-action" as described above, where the user is encouraged to update his/her data ("It's been four days since you last told us about your health situation. If there has been any change, please let us know by updating your data below!"

**Comment by adriaandotcom** [comment]
>I also think we should implement the "call-to-action" as described above, where the user is encouraged to update his/her data ("It's been four days since you last told us about your health situation. If there has been any change, please let us know by updating your data below!"

Yes, created an other issue for that: https://github.com/BustByte/coronastatus/issues/252
