### ISSUE TITLE
Add a field to the configuration with the language you want to be running

### ISSUE THREAD

**Issue by michaelmcmillan** [BustByte/coronastatus.no#180]

**Comment by fossecode** [comment]
The language is selected based on the `Accept-Language`-header. I think most browsers sets this header. But we could probably set a fallback language in the config

**Comment by adriaandotcom** [comment]
I think it should be based on the domain/server/config, right? And then a selector/dropdown somewhere where visitors can change it.

**Comment by michaelmcmillan** [comment]
With one instance per site, which is what we now have, couldn't we just let the tld (.no/.nl) decide the language? Aka. a config field for the server?

**Comment by fossecode** [comment]
Yeah, but i18n selects language based on the `Accept-Language` header, which essentially means the language of the users browser. If we don't support the language, we need a fallback language. This should be specified in a config.

I18n also supports overriding the browser language by using a cookie, we can add this if we want the user to be able to select language themselves.
