### ISSUE TITLE
Add social media images for The Netherlands

### ISSUE THREAD

**Issue by adriaandotcom** [BustByte/coronastatus.no#181]
Let's make some media images for social media (these are the .no ones):

<kbd><img width="560" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/77236544-d8e47d80-6bbf-11ea-8096-f67eb511e3b8.png"></kbd>

<kbd><img width="560" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/77236546-df72f500-6bbf-11ea-9d01-443db0a6ef6a.png"></kbd>

**Comment by gavinhewitt** [comment]
I can do that. I just need text input?

**Comment by fossecode** [comment]
@gavinhewitt / @adriaanvanrossum any progress here? We should probably add this before we start marketing the dutch site.

**Comment by adriaandotcom** [comment]
Yes indeed! This could be the text in Dutch:

> Maak samen inzichtelijk waar corona is, en waar niet.
> Vul het formulier in (klachten of geen klachten)!
> coronastatus.nl

Is this enough for you @gavinhewitt?

**Comment by gavinhewitt** [comment]
Yes, starting work on it now @adriaanvanrossum @fossecode 

Are we keeping the same design for all languages? (I would think so). Also, I see 2 versions. Do we need both versions localized?

**Comment by fossecode** [comment]
@gavinhewitt we only need one. We wanted to test different image on Facebook and Twitter, but only one is needed.

**Comment by gavinhewitt** [comment]
![image](https://user-images.githubusercontent.com/1969103/77260312-5b844000-6c87-11ea-8796-f794fd8652ae.png)

Something like this? Or keep same format as above?

**Comment by gavinhewitt** [comment]
![image](https://user-images.githubusercontent.com/1969103/77260495-a81c4b00-6c88-11ea-9dd4-e586b3eb326d.png)
Like this?

**Comment by fossecode** [comment]
Looks good to me (but I dont speak dutch)

**Comment by adriaandotcom** [comment]
Let's go for it! We can always change it later **if** the design of the website changes.

**Comment by gavinhewitt** [comment]
Cool. Will create a pull request for it!

I wanted to make a combination of the 2 images, so incorporate the logo as well, but I found myself struggling to make it work. Decided just to copy the existing one.

**Comment by Kilian** [comment]
PR merged!
