### ISSUE TITLE
Make sure we use sex instead of gender

### ISSUE THREAD

**Issue by adriaandotcom** [BustByte/coronastatus.no#202]
> Pieter: Also it needs to be Sex: Male or Female not Gender, or twitter ppl get angry (not me)

> Michael: haha the pushback we got from some people on that was a little surprising, but yes, I guess better safe than sorry

https://t.me/onzecorona/718

**Comment by Kilian** [comment]
The design didn't use the translations :) Fixed in english, dutch was already ok (using "Sekse")
