### ISSUE TITLE
Add NL and EU logo

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#208]
@arildwtv

**Comment by arildwtv** [comment]
I'll fix this.

**Comment by arildwtv** [comment]
I propose an easier solution. What if we only use the virus icon svg and render the text part (Coronastatus.no/.nl/etc) in HTML? That way we don't need SVGs for every country. @fossecode

**Comment by fossecode** [comment]
Yeah thats a good idea. Makes it less tedious to add more countries. Could you create the logo without TLD @arildwtv?

**Comment by arildwtv** [comment]
On it. So just the virus icon, right? @fossecode

**Comment by adriaandotcom** [comment]
You could use something like this (don't mind the arrow):

![CleanShot 2020-03-22 at 15 19 54@2x](https://user-images.githubusercontent.com/1079135/77251773-9e76f100-6c50-11ea-87a5-e05baf580a5e.jpg)

But feel free to do whatever you want :)

**Comment by arildwtv** [comment]
@adriaanvanrossum Until we decide on a final design, I'll just "clone" the current logo we're using, hope that's ok. :) 

@fossecode Where do we provide the tld parameter? Should we define it in `example.json` as `TLD`? We already have a `LANGUAGE` config parameter, but these aren't necessarily one-to-one.

**Comment by arildwtv** [comment]
https://github.com/BustByte/coronastatus/pull/217/files
