### ISSUE TITLE
BUG: Siden viser feilmelding ved navigering til `les mer` for personvern siden

### ISSUE THREAD

**Issue by JonasJore** [BustByte/coronastatus.no#21]
Siden om for les mer om personvern viser bare: `Cannot GET /personvernerkl%C3%A6ring`

**Comment by fossecode** [comment]
Takk for feedback, fikset i https://github.com/BustByte/coronastatus.no/commit/1ea2deac58a8d19fea966d3d6525bf725852321b

Deployes as we speak
