### ISSUE TITLE
Make URL to definition of "near contact" configurable by country

### ISSUE THREAD

**Issue by arildwtv** [BustByte/coronastatus.no#212]
Right now, we're linking to FHI (Norwegian Institute for Public Health) for the definition of "near contact". This should be configurable for each country.

Also, is "near contact" a known term outside Norway?

**Comment by Kilian** [comment]
We have the translations for that without the link, see locale files

Dutch: nauwe contacten
English: close contacts

**Comment by fossecode** [comment]
Part of translation now, closing the issue.
