### ISSUE TITLE
Add a Dutch wordlist for generating human readable passcodes

### ISSUE THREAD

**Issue by michaelmcmillan** [BustByte/coronastatus.no#234]
Currently we generate passcodes by picking random words from [wordList.txt](https://github.com/BustByte/coronastatus/blob/master/wordList.txt). This word list is in Norwegian only. So we need to adapt the code to look at what language the config wants the app to use and then load a word list for that language.

1. Get a hold of a Dutch word list without any curse words
2. Add it to `app/locales/nl-wordList.txt`
3. Move the original `wordList.txt` to `app/locales/no-wordList.txt`
4. Change the code to look at the config when loading the word list

**Comment by jelbazi** [comment]
As I understand it, the code currently uses 3 words as a passcode. For a big list like the Norwegian (20k words?), that's fine.
For the current WIP Dutch list (which Stano translated from bitcoin mnemonic) that's not enough.

So I see 2 roads we can take,

1. create another list from a dictionary (e.g., www.gwicks.net/textlists/nederlands.zip) and filter out some words.

2. use the shorter list, but use more words for the passcode.

Thoughts?

Btw, I am inclined towards nr 1. So we don't have to have different logical implementations of code.

**Comment by adriaandotcom** [comment]
You could use option 1 and apply this:

Remove all words containing:
- tering
- kanker
- penis
- mastur
- neuk

Words being:
- anaal

Start with:
- kut
- tepel

Would also check if any words contain non a-z characters, saw a few.

**Comment by jelbazi** [comment]
Alright, on it.

**Comment by Kilian** [comment]
PR merged, closing this!
