### ISSUE TITLE
Send optional email with passcode to user

### ISSUE THREAD

**Issue by arildwtv** [BustByte/coronastatus.no#236]
Should we maybe support sending on-demand email with the passcode / profile URL? Consider a user who has just submitted the form. We could allow him/her to enter his/her email address, to which we will send the passcode / profile URL. As long as it is optional and we explicitly inform the user that we do not store any link between email and health details, this should be perfectly fine, I believe.

Purpose: To increase conversion rate of users updating their reports.

**Comment by adriaandotcom** [comment]
From https://github.com/BustByte/coronastatus/issues/172

> I also think we should implement the "call-to-action" as described above, where the user is encouraged to update his/her data ("It's been four days since you last told us about your health situation. If there has been any change, please let us know by updating your data below!"

We could make a banner on every page of the website (now it's only on when when people don't use a cookie). 

We could also ask for an email (I think it's better) so we can send people a reminder. We could include the link in their email so they don't have to think about it anymore.

**Comment by fossecode** [comment]
Duplicates https://github.com/BustByte/coronastatus/issues/259
