### ISSUE TITLE
Text in 'Symptoms' chart is Norwegian on .nl

### ISSUE THREAD

**Issue by gavinhewitt** [BustByte/coronastatus.no#241]
![image](https://user-images.githubusercontent.com/1969103/77260864-d3079e80-6c8a-11ea-972a-7e765ab8fc15.png)

**Comment by fossecode** [comment]
Duplicates https://github.com/BustByte/coronastatus/issues/211

**Comment by Kilian** [comment]
closing this in favor of #211
