### ISSUE TITLE
Dutch site should mention post code should be without characters

### ISSUE THREAD

**Issue by Kilian** [BustByte/coronastatus.no#246]
Dutch postal codes are in the form 0000AA, but the AA is not needed.

Possibly for the dutch site only, is there a way to do this neatly? (we could do if statements in the template but that doesn't sound great. @fossecode ideas?)

**Comment by fossecode** [comment]
Hmm, I don't know. Maybe something like this
```ejs
<div class="col-5 col-12-small input-block">
  <label class="with-top-margin" for="postal-code"><%= __('Zip code') %></label>
  <%- __('Zip code information') ? `<p class="info">${__('Zip code information')}</p>` : '' %>
  <input required type="text" pattern="[0-9]{4}" maxlength="4" name="postal-code" id="postal-code" placeholder="1234" value="<%= postalCode %>">
</div>
```
And then write the info in 'Zip code information'. That way it can just be left empty for countries that don't need it. But it feels a bit weird

**Comment by fossecode** [comment]
The pattern-validation must probably be removed or changed (not for NL, but for others)

**Comment by Kilian** [comment]
pattern could also be translatable?

**Comment by Kilian** [comment]
The issue with the translation is that it should work for the dutch site in both languages but not for english elsewhere (difference between i18n and l10n.)

**Comment by michaelmcmillan** [comment]
I think it's cleaner to just have a switch/if inside the template based on the language set in the config?

**Comment by fossecode** [comment]
Yeah, didn't think about that. Agree with @michaelmcmillan

**Comment by Kilian** [comment]
Will do that!

**Comment by Kilian** [comment]
..I can just make it part of the translation and that works too. d'oh.

**Comment by Kilian** [comment]
...doesn't solve the issue for english-on-nl site, but this is easy enough and we also have the pattern match and placeholder to help guide users.
