### ISSUE TITLE
Create ads and meta images with new design in mind

### ISSUE THREAD

**Issue by adriaandotcom** [BustByte/coronastatus.no#250]
I think if there is one that fits all, or at least one that fits the aspect radio of these (with some bleed):

![](https://via.placeholder.com/2048x1024.png?text=Twitter+2048+x+1024px)

![](https://via.placeholder.com/2400x1256.png?text=Facebook+2400+x+1256px)

<img src="https://via.placeholder.com/400x400.png?text=Twitter+avatar+400+x+400px" width="200px">

![](https://via.placeholder.com/1456x180.png?text=Ad+banner+1456+x+180px)

Pixels are doubled for retina screens.

According https://sproutsocial.com/insights/social-media-image-sizes-guide

cc @amritnagi

**Comment by fossecode** [comment]
If I remember correctly, this is done?
