### ISSUE TITLE
Add call to action button on top of page

### ISSUE THREAD

**Issue by adriaandotcom** [BustByte/coronastatus.no#253]
With the text "Contribute now"

https://t.me/onzecorona/1434

![telegram-cloud-photo-size-4-6034874143092093937-y](https://user-images.githubusercontent.com/1079135/77324579-3fc87a80-6d17-11ea-8f0b-7bf7a2765a94.jpg)

**Comment by amritnagi** [comment]
Proposed:

![image](https://user-images.githubusercontent.com/25029371/77332303-d138ec00-6d19-11ea-9511-3ed37b597944.png)

![image](https://user-images.githubusercontent.com/25029371/77332326-d72ecd00-6d19-11ea-8b29-57c959bbc51c.png)
