### ISSUE TITLE
Create a dropdown where user can select their country

### ISSUE THREAD

**Issue by michaelmcmillan** [BustByte/coronastatus.no#260]
<img width="1429" alt="Screenshot 2020-03-23 at 19 11 16" src="https://user-images.githubusercontent.com/147197/77348651-1ec55100-6d3a-11ea-9ab3-68b8eaddcab7.png">

**Comment by ewels** [comment]
See https://gist.github.com/mashpie/08e5a0ee764f7b6b1355 for an example implementation in the back end.

**Comment by fossecode** [comment]
Fixed in #448
