### ISSUE TITLE
Revised options under "I am currently" in form

### ISSUE THREAD

**Issue by arildwtv** [BustByte/coronastatus.no#262]
I think we should have these options under "I am currently":

* Not in isolation
* In isolation due to COVID-19 infection
* In isolation due to a recent international travel
* In isolation due to contact with an individual who has been exposed to the coronavirus

**Comment by arildwtv** [comment]
Should we distinguish between quarantine and isolation?

**Comment by fossecode** [comment]
I suspect distinguishing between quarantine and isolation can be confusing for people. Tbh I am not sure about the difference myself.

**Comment by jelbazi** [comment]
There are people in isolation that chose to do so out of themselves.
Then there are people doing it when there is a lockdown.

But that may be too many options.

Also (maybe it is wrong to assume) but if someone answers they have been tested positive with COVID (in another question), they will self-isolate.

Maybe an option for "in isolation for other reasons related to COVID19."?

**Comment by jelbazi** [comment]
What do you guys think is the chance of people self- "diagnosing" and saying they are in isolation because they think they have COVID-19?

Could be happening if we have the option for, "In isolation due to COVID-19 infection." But maybe it's not a problem.

**Alternatively, we could have the below list:**
    - Not in isolation
    - In isolation due to a recent international travel
    - In isolation due to contact with an individual who has been exposed to the coronavirus
    - In isolation due to other reasons related to COVID-19 👈 Less specific but also usable by people that are infected.

**Or just all 5 options:**
    - Not in isolation
    - In isolation due to COVID-19 infection
    - In isolation due to a recent international travel
    - In isolation due to contact with an individual who has been exposed to the coronavirus
    - In isolation due to other reasons related to COVID-19

Is that too much?

**Comment by arildwtv** [comment]
> What do you guys think is the chance of people self- "diagnosing" and saying they are in isolation because they think they have COVID-19?

I know many people from work who have done this. They have been in close contact with a person who has tested positive, and they have developed symptoms, but the government does not have the capacity to test them.

And also, as a COVID-19 infected, I was looking for the option "due to COVID-19 infection". Personally, I would think it slightly unintuitive to choose "due to other reasons related to COVID-19".

How about changing the question into two questions, like we do with the corona test question?

*Are you currently in isolation?*
- Yes
- No

*Why are you in isolation?*
- COVID-19 infection
- Recent international travel
- Contact with an individual who has been tested positive for COVID-19
- Other reason

The second question only pops up if you answer "Yes", which reduces mental load. Also, this structure makes for easier filtering of data.

**Comment by jelbazi** [comment]
Splitting it up is a good idea I think. And the way you state it is looking clear.

There is one (maybe two) possible issue though, which is that earlier in the form the user is already asked if they have been in contact with an infected person.
Second (and it is the case without splitting the questions up), is what if people are in a situation where multiple answers apply?

**Comment by arildwtv** [comment]
> There is one (maybe two) possible issue though, which is that earlier in the form the user is already asked if they have been in contact with an infected person.

Yeah, I agree. If we removed that question, I wouldn't object.

But also, consider the state of the data for a given person in two-three weeks time. The person *was* in close contact with an infected individual three weeks ago, but did not develop symptoms. So, after these three weeks, the person checks off that he no longer is in isolation ("Are you currently in isolation?": "No"), but still answers "Yes" to the "close contact" question. The question is whether or not this is interesting data, what do you think?

> Second (and it is the case without splitting the questions up), is what if people are in a situation where multiple answers apply?

I would advise them to pick whatever option is most relevant.
