### ISSUE TITLE
Scroll to success message after confirming profile

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#273]
After reporting and confirming a profile on a phone, you are redirected to your profile. There is also a success message, but it is located far down on the page. We should probably scroll down to the success message.

**Comment by fossecode** [comment]
[scroll-to-success-message.MP4.zip](https://github.com/BustByte/coronastatus/files/4375057/scroll-to-success-message.MP4.zip)

**Comment by adriaandotcom** [comment]
just add #contribute to the redirect url

**Comment by adriaandotcom** [comment]
fixing now

**Comment by adriaandotcom** [comment]
Done: https://github.com/BustByte/coronastatus/pull/286
