### ISSUE TITLE
Buttons, info message and link looks very similar on the confirm profile page

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#274]
Might be confusing for users. Do the link have to placed in a input field? Could we just display it instead? The text and the copy button should maybe have full width on small screens as well.

![IMG_2740](https://user-images.githubusercontent.com/8818089/77423257-271b9b80-6dcf-11ea-87cc-a43ebd517a98.PNG)

**Comment by adriaandotcom** [comment]
Having to copy something out of an input field in very common in The Netherlands. But most people will use the kopier button I think.

**Comment by janmande** [comment]
It used to be a span, so it does not have to be an input box.

**Comment by adriaandotcom** [comment]
I'm okay if it's changed to whatever. As long as people can also copy it easily when the copy button does not work. That's why it was an input. Inputs are more easy to copy then normal text.

**Comment by amritnagi** [comment]
Do you think having a button to send the link via email would be an useful additional option here?

Fyi I've restyled in the button in pr 511.
https://github.com/BustByte/coronastatus/commit/47b43865603ae211d3add987ab97ddf9af48c040

**Comment by adriaandotcom** [comment]
Email is discussed here https://github.com/BustByte/coronastatus/issues/259 and would be great, but it's not very privacy friendly if we just use one provider.
