### ISSUE TITLE
Make input box not red, seems invalid

### ISSUE THREAD

**Issue by adriaandotcom** [BustByte/coronastatus.no#300]
<img src="https://user-images.githubusercontent.com/1079135/77472160-c9f60900-6e13-11ea-9dbe-ca875284054a.jpg" width="320px">

**Comment by fossecode** [comment]
Does it have to be an input box at all? Relates to https://github.com/BustByte/coronastatus/issues/274

**Comment by janmande** [comment]
It used to be a span, so no, it does not have to be an input box.

**Comment by adriaandotcom** [comment]
Duplicate of https://github.com/BustByte/coronastatus/issues/274
