### ISSUE TITLE
Time of symptoms

### ISSUE THREAD

**Issue by adriaandotcom** [BustByte/coronastatus.no#303]
Some feedback I got from people: you kind of have to know when those symptoms where taking place. Now? One week ago? 3 weeks ago?

**Comment by fossecode** [comment]
Hmm, what do you mean? More specific than what we already have?
![image](https://user-images.githubusercontent.com/8818089/77518414-0eb68a00-6e7e-11ea-9364-bac925d6dcfb.png)

**Comment by adriaandotcom** [comment]
Hm, that's weird, not sure why people would ask this then.

**Comment by fossecode** [comment]
It does not show if you don't check any symptoms, so I guess the people who reported it didn't have any symptoms.
