### ISSUE TITLE
Replace form with link to form at helsenorge.no

### ISSUE THREAD

**Issue by henrist** [BustByte/coronastatus.no#307]
Follow-up on #143

The official national form for Norway has been launched a few days ago:
https://minhelse.helsenorge.no/skjemautfyller?Query=Questionnaire/302

Probably the other pages should have a banner as well telling the data is for previous registation before the form was disabled.

I also advice to add text to encourage people that have already registered to also register at helsenorge.no. The problem now is that we possibly have 7000+ people who think they have already registered, and do not understand they need to go to helsenorge.no _as well_. Not all people will see this text, but it will make it explicit and easier to communicate.

**Comment by fossecode** [comment]
https://github.com/BustByte/coronastatus/pull/304
