### ISSUE TITLE
Nothing option in the symptoms

### ISSUE THREAD

**Issue by zerbfra** [BustByte/coronastatus.no#324]
It would be nice to have the option for "nothing" in the symptoms checkboxes.

**Comment by zerbfra** [comment]
labels: enhancement,

**Comment by Kilian** [comment]
This would mean a bunch of additional logic, since we'd need to prevent people from selecting both "Nothing" and "Dry Cough". Perhaps we can make it more clear in all languages (like Norwegian) that it's ok to check none if you have no symptoms.

**Comment by zerbfra** [comment]
For now I’ve don it in the question string (in the italian transaltion)

**Comment by fossecode** [comment]
Yes, France has also made this clear in the text above the checkboxes. I think that is the easiest solution for now.
