### ISSUE TITLE
Longitudinal tracking

### ISSUE THREAD

**Issue by ewels** [BustByte/coronastatus.no#326]
The app currently collects repeated entries under the same passcode, essentially building a time series of responses from each person. I think that this is a huge opportunity for getting useful data - with repeat responses we can track the progression through different symptoms: severity, speed of progression and other factors.

Other comparable tools appear to be aiming for this, for example the UK based [COVID Symptom Tracker](https://covid.joinzoe.com/) (top tagline: _Self-report daily._, TechCrunch article on this tool [here](https://techcrunch.com/2020/03/25/self-reporting-app-for-covid-19-symptoms-for-uk-research-sees-650k-downloads-in-24-hours/). [Let's Beat Covid19](https://letsbeatcovid.net/) does the same (_Tell us what's changed, Update your status_) and [Evergreen Life](https://www.evergreen-life.co.uk/covid-19-heat-map) is an app that pings notifications to people for repeat surveys.

All of the main pieces seem to be in place for this in the app here, but I think some things need strengthening:

1. More emphasis needs to be put on repeat survey completions
2. The completed message needs to request that people come back the next day
3. Optional non-identifying tools could potentially remind people potentially?
4. Longitudinal analysis of these results.

Suggestions and feedback welcome!

**Comment by mihai-sysbio** [comment]
Do any of these tools mention what data they make available, and to whom? From what I could find it sounds they are fairly closed.

**Comment by ewels** [comment]
I think that they’re quite closed, yes. I think it’s the TC article that mentions that data is anonymised before sharing if anyone requests it (or something). I think immediate sharing via API + download as we have here is much better 👍 

But mostly I think it’s just interesting to compare interfaces and focus.

**Comment by ewels** [comment]
Closing as I realise now that this issue is essentially a dup of several others: https://github.com/BustByte/coronastatus/issues/245#issuecomment-602480544 https://github.com/BustByte/coronastatus/issues/173 https://github.com/BustByte/coronastatus/issues/184 https://github.com/BustByte/coronastatus/issues/259
