### ISSUE TITLE
We need the privacy banner on mobile

### ISSUE THREAD

**Issue by zerbfra** [BustByte/coronastatus.no#328]
We need the privacy banner (or in the menu) on mobile devices

**Comment by fossecode** [comment]
Could you elaborate? Do you mean a link to the privacy statement in the menu?

**Comment by amritnagi** [comment]
The yellow banner, we made it hidden on mobile, easy enough to display it.

Although if it's taking up too much space, we can look to redesign the two bars on mobile to display differently

**Comment by zerbfra** [comment]
Yes, it should be redesigned

**Comment by fossecode** [comment]
Fixed in #345
