### ISSUE TITLE
Generate social media images

### ISSUE THREAD

**Issue by Kilian** [BustByte/coronastatus.no#352]
Instead of working in the figma file, we can generate the social media images using HTML and puppeteer. That way the strings can just be part of this repo and creating new ones is easy.

I'll get started on this in a couple of hours.

**Comment by michaelmcmillan** [comment]
Figma also has a great REST API that I think could be used to change the text in a file + export to svg/png

**Comment by Kilian** [comment]
If we rebuild the images in HTML we get translations + line-wrapping etc for free, then a puppeteer script is a single command to output new images. I think that scales better (someone with experience with figma might have a different opinion)

**Comment by adriaandotcom** [comment]
I think you just like to build this little feature ;)

We also need more sharing options btw, but yeah. It also needs to be fun for yourself ;)

**Comment by Kilian** [comment]
awesome idea by @michaelmcmillan: v2 could embed the map in the background for an even more customised image.

**Comment by Kilian** [comment]
Merged, can be closed!
