### ISSUE TITLE
Custom Datepicker to report symptoms start date

### ISSUE THREAD

**Issue by zerbfra** [BustByte/coronastatus.no#369]
We need a custom datepicker since the default one is not supported on all browsers (Safari -.-).

https://caniuse.com/#feat=input-datetime

label: enhancement

**Comment by fossecode** [comment]
Can believe I actually suggest this, but could we just fix it quick with https://api.jqueryui.com/datepicker/?

**Comment by michaelmcmillan** [comment]
What about? https://github.com/flatpickr/flatpickr

**Comment by fossecode** [comment]
Fixed in #491
