### ISSUE TITLE
All radio buttons and checkboxes have bold text

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#376]
I think that was changed by accident?

## Before:
![coronastatus nl Tablet_polypane](https://user-images.githubusercontent.com/8818089/77681216-55e36e80-6f95-11ea-8fe3-ff7d47cb1e66.png)

## After:
![coronastatus mx Tablet_polypane2](https://user-images.githubusercontent.com/8818089/77681225-5845c880-6f95-11ea-9201-9a1dbb82818e.png)

**Comment by Kilian** [comment]
Fix pushed!

**Comment by Kilian** [comment]
ref: https://github.com/BustByte/coronastatus/commit/b0fe8064f1cdbf8d9f8fe75c7223f4a65143f78c

**Comment by fossecode** [comment]
Awesome, thanks :)
