### ISSUE TITLE
Translate to Bahasa Melayu

### ISSUE THREAD

**Issue by jinjie** [BustByte/coronastatus.no#417]
Need help on translating to Bahasa Melayu

https://github.com/BustByte/coronastatus/blob/master/app/locales/ms-MY.json

**Comment by jinjie** [comment]
Need someone to help review the translations: https://gist.github.com/jinjie/753ee1c786bf005b48b9ff2bd83d914e

Mostly translated using Google Translate but was informed that some phrases looked weird and doesn't match the translation... 😞

**Comment by michaelmcmillan** [comment]
Hey, great work! Do you know anyone who speaks Malay?

**Comment by jinjie** [comment]
Yes. I have approached a few. Hopefully to update soon.

Regards,
Kong Jin Jie
