### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [BustByte/coronastatus.no#423]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the Open-Source-COVID-19 page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

http://open-source-covid-19.weileizeng.com/

Cheers!

**Comment by adriaandotcom** [comment]
Thanks @WeileiZeng!

**Comment by bertrandlalo** [comment]
@WeileiZeng, thank's for sharing the website, I went through some of the projects you found and recommended, it's awesome!   
For this one (_coronastatus_), it may be more appropriate to put the project in part **"API, data"**, since the first purpose is a crowdsourcing! 
Best!

**Comment by WeileiZeng** [comment]
> @WeileiZeng, thank's for sharing the website, I went through some of the projects you found and recommended, it's awesome!
> For this one (_coronastatus_), it may be more appropriate to put the project in part **"API, data"**, since the first purpose is a crowdsourcing!
> Best!

Thanks. Changed.
