### ISSUE TITLE
Statistic page not displaying numbers

### ISSUE THREAD

**Issue by julianbetancourt** [BustByte/coronastatus.no#484]
Some sites are not displaying numbers on the stats. Example:

![image](https://user-images.githubusercontent.com/11728570/77862171-0d88b280-721a-11ea-8f39-797e33abf873.png)

----

![image](https://user-images.githubusercontent.com/11728570/77862177-14172a00-721a-11ea-813a-aef55287f232.png)

Surprisingly, the .nl is displaying the numbers as normal:

![image](https://user-images.githubusercontent.com/11728570/77862195-285b2700-721a-11ea-8872-11bad6fa37f9.png)

**Comment by fossecode** [comment]
I think @adriaanvanrossum has fixed this, so we should probably try to release the other countries as well.

**Comment by adriaandotcom** [comment]
Jep, this is fixed in https://github.com/BustByte/coronastatus/pull/479. I think @michaelmcmillan can do this deploy to other countries as well.
