### ISSUE TITLE
Move country or domain specific domains out of locales

### ISSUE THREAD

**Issue by jinjie** [BustByte/coronastatus.no#509]
I propose that we move the country names, health agency name, domain names out of the translation file.

Since there is multiple language per country, there will come a case where, a country do not have it's own english locale. For example, there is no locale code of "en-MY". We may think that it is English (Malaysia) but based on the list of locales, there is no such locale at all: https://github.com/mozilla/language-mapping-list/blob/master/language-mapping-list.js

Since it is still english, we may choose to include en-US for Malaysia. When we do that, we will see something like:

> Fill out this form - it takes 1 minute - and help the United States gain control over COVID-19.

Which is wrong.

I feel there is advantages by improving how we improve the locales. Such as the possibility of switching to an available locale as detected on the browser.

**Comment by fossecode** [comment]
Ahh good point, didn't think about that.

**Comment by jinjie** [comment]
Is it difficult to achieve this? We can still manage with the current locale setup, but it may become a mess when more countries and locales join in.

We will also see a lot of duplicated locale files. For example, I am using en-SG for English (Singapore). In fact, I can easily use en-UK for Singapore.

**Comment by fossecode** [comment]
Fixed in #537
