### ISSUE TITLE
Words for personal URL should be optimized

### ISSUE THREAD

**Issue by ceremcem** [BustByte/coronastatus.no#545]
Words being used for generating personal URL's should be cleaned up by 
* Removing possibly offensive words (akkefal, etc.) (any offensive word prefixed by `ak`)
* Removing uncommon words (adenit, aforizm, ehram, etc.)
* Removing duplicates (adenit)

In general, those words to build personal URL's can't be selected more poorly. 

@btutal

**Comment by btutal** [comment]
Why do you think uncommon words should be removed? Duplicate can be deleted but I don't agree with other points.

**Comment by btutal** [comment]
I've removed duplicate word in 4b4c5a015a523e2aea244332c6e7978761f8278f closing this issue since if the word is common or uncommon is not relevant with usage and words that start with `ak` is not offensive.
