### ISSUE TITLE
Add hamburger menu on small devices

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#55]

**Comment by randriana** [comment]
I can take this :)

**Comment by randriana** [comment]
Ser ikke ut som jeg får assignet den selv?

**Comment by fossecode** [comment]
Great :) The regular menu is located here, I suppose the hamburger menu should contain the same items: https://github.com/BustByte/coronastatus.no/blob/master/app/views/partials/menu.ejs
