### ISSUE TITLE
Online Configuration

### ISSUE THREAD

**Issue by rafaelsabino** [BustByte/coronastatus.no#557]
Good night, can I have this site only in docker container format? I would like to implement it on the web, but I don't know anything about docker. Is there another way to leave on shared server?

**Comment by fossecode** [comment]
Hi, we can host it for you if want. What country are you from?

**Comment by rafaelsabino** [comment]
Good afternoon. It would help me a lot. I realized that there is one installed for Brazil. But it is general. I am from Brazil in the city of São Paulo and I would like the form to be used only here. It would be great to account for local cases. What would this configuration look like on my server for me to use in my city and send to as many people as I can?
