### ISSUE TITLE
Host coronastatus.gr | Hellenic Republic (Greece) 🇬🇷

### ISSUE THREAD

**Issue by estamos** [BustByte/coronastatus.no#565]
A Greek translation is finally fully functional.
I run `yarn lint`with output : `✨  Done in 3.44s.`

Could you host coronastatus.gr ? 
Source can be found [here](https://github.com/estamos/coronastatus-gr).

el-GR | GR 🇬🇷

**Comment by michaelmcmillan** [comment]
We do not have any credit to give unfortunately. If you want to host it simply follow the instructions in the ops/ directory in the repository.
