### ISSUE TITLE
Show info box on front page when "hasSubmittedProfile" exists in localStorage

### ISSUE THREAD

**Issue by fossecode** [BustByte/coronastatus.no#86]
Inform user that a profile might already exist, and inform that they should use the URL they got when they first registered.

It could be a new user in the same browser, so it should not be too intrusive.

**Comment by fredrikpe** [comment]
![info-bar](https://user-images.githubusercontent.com/3830767/76835893-324f5400-6830-11ea-9213-6ce53e861419.png)

**Comment by fredrikpe** [comment]
![info-bar-v2](https://user-images.githubusercontent.com/3830767/76836171-a558ca80-6830-11ea-8bc7-a11080a516b9.png)
